# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e82428af8832c815ae4c87cda825da26a079eb9ff1e0344245133871f698013c43c06f1075ca617c3edf98c7f90e511e0f2c32affc8c529ed2f1994a55fb28

test:
  secret_key_base: 4ca86061a35eef1a841624d1cfbfec15f4e403fdec10fbd051da1461a137d4209cd654c33beedb9afc15c826b9dce4ac48dc874c4b5fbbdac5af3a73ecc6e6d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
